theme: jekyll-theme-cayman
title: "RoboSoft'25: The 1st International Workshop on Vision-Language in Soft Robot"

description:
- ACM Multimedia 2025 Workshop
- October 28, 2025
- Dublin, Ireland

buttons:
  Overview: './index.html'
  Schedule: './schedule.html'
  Call for Papers: './call4papers.html'
  Challenge: './challenge.html'
github:
  is_project_page: false
